### ISSUE TITLE
It made the SytemUI stop running

### ISSUE THREAD

**Issue by Cryolitia** [paphonb/AndroidP-ify#107]
**Description**
The SystemUI stop running

**Steps to reproduce**
I just enabled it and reboot.

**ROM info**
AOSP 8.0 on Genymotion virtual device

**Module version (build version)**
150

**Xposed log / logcat**

```
08-06 03:25:57.232 1773-1773/com.android.systemui E/Xposed: de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.systemui.qs.tileimpl.SlashImageView
        at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:71)
        at xyz.paphonb.androidpify.hooks.QuickSettingsHook$classSlashImageView$2.invoke(QuickSettingsHook.kt:65)
        at xyz.paphonb.androidpify.hooks.QuickSettingsHook$classSlashImageView$2.invoke(QuickSettingsHook.kt:49)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
        at xyz.paphonb.androidpify.hooks.QuickSettingsHook.getClassSlashImageView(Unknown Source:8)
        at xyz.paphonb.androidpify.hooks.QuickSettingsHook.handleLoadPackage(QuickSettingsHook.kt:732)
        at xyz.paphonb.androidpify.MainHook.handleLoadPackage(MainHook.kt:56)
        at xyz.paphonb.androidpify.XposedHook.handleLoadPackage(XposedHook.kt:34)
        at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
        at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
        at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
        at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:134)
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
        at android.app.ActivityThread.handleBindApplication(<Xposed>)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
     Caused by: java.lang.ClassNotFoundException: com.android.systemui.qs.tileimpl.SlashImageView
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
        at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:69)
        at xyz.paphonb.androidpify.hooks.QuickSettingsHook$classSlashImageView$2.invoke(QuickSettingsHook.kt:65) 
        at xyz.paphonb.androidpify.hooks.QuickSettingsHook$classSlashImageView$2.invoke(QuickSettingsHook.kt:49) 
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131) 
        at xyz.paphonb.androidpify.hooks.QuickSettingsHook.getClassSlashImageView(Unknown Source:8) 
        at xyz.paphonb.androidpify.hooks.QuickSettingsHook.handleLoadPackage(QuickSettingsHook.kt:732) 
        at xyz.paphonb.androidpify.MainHook.handleLoadPackage(MainHook.kt:56) 
        at xyz.paphonb.androidpify.XposedHook.handleLoadPackage(XposedHook.kt:34) 
        at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34) 
        at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61) 
        at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106) 
        at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:134) 
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341) 
        at android.app.ActivityThread.handleBindApplication(<Xposed>) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.systemui.qs.tileimpl.SlashImageView" on path: DexPathList[[zip file "/system/priv-app/SystemUI/SystemUI.apk"],nativeLibraryDirectories=[/system/priv-app/SystemUI/lib/x86, /system/lib, /system/vendor/lib, /system/lib, /system/vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:453) 
        at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823) 
        at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:69) 
        at xyz.paphonb.androidpify.hooks.QuickSettingsHook$classSlashImageView$2.invoke(QuickSettingsHook.kt:65) 
        at xyz.paphonb.androidpify.hooks.QuickSettingsHook$classSlashImageView$2.invoke(QuickSettingsHook.kt:49) 
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131) 
        at xyz.paphonb.androidpify.hooks.QuickSettingsHook.getClassSlashImageView(Unknown Source:8) 
        at xyz.paphonb.androidpify.hooks.QuickSettingsHook.handleLoadPackage(QuickSettingsHook.kt:732) 
        at xyz.paphonb.androidpify.MainHook.handleLoadPackage(MainHook.kt:56) 
        at xyz.paphonb.androidpify.XposedHook.handleLoadPackage(XposedHook.kt:34) 
        at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34) 
        at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61) 
        at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106) 
        at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:134) 
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341) 
        at android.app.ActivityThread.handleBindApplication(<Xposed>) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108) 
```

**Comment by drkui** [comment]
I'm getting the same problem. I just enabled the module, reboot, and then I get the black screen.

I'm running Stock 8.0 on the  LG G5 (H830). Tested using v153 of the module.

**Comment by mochaaP** [comment]
same:cry:
